#!/bin/bash

cmd=("$@")

bgo='0.75'

# main
case ${cmd[0]} in
	"muspick") script='mp' ;;
	*) echo "[dsh!] unrecognized desktop shell script [ ${cmd[0]} ]"; echo "[dsh/] aborting"; exit 1 ;;
esac

kitty -o background_opacity="$bgo" --title dsh:w:"${cmd[0]}" "$script" "${cmd[@]:1}"
