#!/bin/bash
cmd=("$@")

### parsing

# repository parser
rep="unset"
prs-rep() {
	local arg=$1
	case "$arg" in
		"@aur")
			rep="AUR"
			;;
		"@pac" | "@pacman")
			rep="pacman"
			;;
		*)
			rep="unknown"
			;;
	esac

}

# function parser
fnc="unset"
prs-fnc() {
	local arg=$1
	case "$arg" in
		"i" | "install")
			fnc="install"
			;;
		"u" | "update")
			fnc="update"
			;;
		"q" | "query")
			fnc="query"
			;;
		"r" | "remove")
			fnc="remove"
			;;
		*)
			fnc="unknown"
			;;
	esac
}

# flag parser
preflg=()
pstflg=()
flgraw=()
prs-flg() {
	local arg=$1
	case "$arg" in
		"h" | "help")
			preflg+=("HELP")
			;;
		"v" | "verbose")
			preflg+=("VERBOSE")
			;;
		"c" | "confirm")
			pstflg+=("CONFIRM")
			;;
		*)
			preflg+=("unknown")
			;;
	esac
}

# subflag parser
sbf=()
sbfraw=()
prs-sbf() {
	local arg=$1
	case "$fnc" in
		"install")
			case "$arg" in
				"q" | "+quiet")
					sbf+=("QUIET")
					;;
				*)
					sbf+=("unknown")
					;;
			esac
			;;
		*)
			sbf+=("unknown")
			;;
	esac
}

# filtering
for i in ${!cmd[@]}; do
	# filter repositories into rep
	if [[ ${cmd[$i]:0:1} == "@" ]]; then
		if [[ "$rep" == "unset" ]]; then
			prs-rep "${cmd[$i]}"
			unset "cmd[$i]"
		else
			echo "[!] multiple repositories specified"
			exit 1
		fi
	# filter flags into flg whilst saving the raw values into flgraw
	elif [[ ${cmd[$i]:0:1} == "-" ]]; then
		if [[ ! ${cmd[$i]:1:1} == '-' ]]; then
			for o in $(echo -n ${cmd[$i]:1} | grep -o .); do
				flgraw+=("$o")
				prs-flg "$o"
			done
		else
			flgraw+=("${cmd[$i]:1}")
			prs-flg "${cmd[$i]:2}"
		fi
		unset "cmd[$i]"
	# filter subflags into temporary array sbfraw
	elif [[ ${cmd[$i]:0:1} == "+" ]]; then
		if [[ ! ${cmd[$i]:1:1} == '+' ]]; then
			for o in $(echo -n ${cmd[$i]:1} | grep -o .); do
				sbfraw+=("$o")
			done
		else
			sbfraw+=("${cmd[$i]:1}")
		fi
		unset "cmd[$i]"
	fi
done

cmd=("${cmd[@]}")

# deduce core function into fnc
if [ ! ${#cmd[0]} == 0 ]; then
	prs-fnc "${cmd[0]}"
	if [[ "$fnc" == "unknown" ]]; then
		fnc="unset"
	else
		unset "cmd[0]"
		cmd=("${cmd[@]}")
	fi
fi

# translate default values
if [[ "$rep" == "unset" ]]; then
	prs-rep "@$(cat ~/.config/nb/nb.conf|grep -Po '(?<=default-repository:).+')"
fi

if [[ "$fnc" == "unset" ]]; then
	if [ ${#cmd[@]} == 0 ]; then
		prs-fnc "$(cat ~/.config/nb/nb.conf|grep -Po '(?<=default-empty-function:).+')"
	else
		prs-fnc "$(cat ~/.config/nb/nb.conf|grep -Po '(?<=default-function:).+')"
	fi
fi

# filter subflags into sbf
for i in ${!sbfraw[@]}; do
	prs-sbf "${sbfraw[$i]}"
done

if [ "${#preflg[@]}" == 0 ]; then
	preflg="none"
fi

if [ "${#pstflg[@]}" == 0 ]; then
	pstflg="none"
fi

if [ "${#sbf[@]}" == 0 ]; then
	sbf="none"
fi

### wrapping

# preflag interpretation
for i in "${!preflg[@]}"; do
	case "${preflg[$i]}" in
		"none")
			;;
		"unknown")
			echo "[!] unknown flag -${flgraw[$i]}"
			exit 1
			;;
		"HELP")
			echo "[.] USAGE: nb [-FLAG] [@REPOSITORY] [FUNCTION] [+SUBFLAG] [PACKAGES]"
			echo "[.] REPOSITORIES: AUR [@aur], PACMAN [@pac], FLATPAK [@fpk]"
			echo "[.] FUNCTIONS: INSTALL [i], UPDATE [u], REMOVE [r], QUERY [q]"
			# flag list
			echo "  -v, --verbose"
			echo "         prints internal information before wrapping"
			echo "  -c, --confirm"
			echo "         asks for confirmation before proceeding to wrapping"
			echo "  -h, --help"
			echo "         prints this message and exits"
			exit 0
			;;
		"VERBOSE")
			echo "[.] REPOSITORY: $rep | FUNCTION: $fnc | preFLAG(s): ${preflg[@]} | postFLAG(s): ${pstflg[@]} SUBFLAG(s): ${sbf[@]}"
			;;
		*)
			echo "[!] catastrophic error at flag interpretation"
			exit 1
			;;
	esac
done

# repository and function interpretation
pkg="${cmd[@]}"
if [ "${#pkg}" == 0 ]; then
	pkg="none"
fi

case "$rep" in
	"pacman")
		case "$fnc" in
			"install")
				sudo pacman -S "$pkg" 
				;;
			"update")
				if [[ "$pkg" == "none" ]]; then
					sudo pacman -Syu
				else
					sudo pacman -Sy "$pkg"
				fi
				;;
			"query")
				pacman -Q "$pkg"
				;;
			*)
				echo "[!] catastrophic error at [PACMAN] function interpretation"
				exit 1
				;;
		esac
		;;
	*)
		echo "[!] catastrophic error at repository interpretation"
		exit 1
		;;
esac

# postflag interpretation
for i in "${!preflg[@]}"; do
	case "${preflg[$i]}" in
		"none")
			;;
		"unknown")
			echo "[!] unknown flag -${flgraw[$i]}"
			exit 1
			;;
	esac
done
