#!/bin/bash

cmd=("$@")

child=0
if [[ "${cmd[0]}" == "--child" ]]; then
	child=1
	unset "cmd[0]"
	cmd=("${cmd[@]}")
fi

if [ "${#cmd[@]}" -gt 1 ]; then
	echo "[cfg!] no more than one argument is accepted"
	echo "[cfg/] aborting"
	exit 1
fi

case "${cmd[0]}" in
	"cfg") $EDITOR ~/.sh/cfg ;;
	"") if [ $child == 0 ]; then $0 --child $(tail -n +18 $0 | grep -oP '^[^"]*"\K[^"]+(?="\s*\))' | fzf); fi ;;
	"bash") $EDITOR ~/.bashrc ;;
	"nb") $EDITOR ~/.config/nb/nb.conf ;;
	"niri") $EDITOR ~/.config/niri/config.kdl ;;
	"niri-monitors") $EDITOR ~/.config/niri/config.d/monitors.kdl ;;
	"niri-input") $EDITOR ~/.config/niri/config.d/input.kdl ;;
	"niri-layout") $EDITOR ~/.config/niri/config.d/layout.kdl ;;
	"niri-cursor") $EDITOR ~/.config/niri/config.d/cursor.kdl ;;
	"niri-startup") $EDITOR ~/.config/niri/config.d/startup.kdl ;;
	"niri-misc") $EDITOR ~/.config/niri/config.d/misc.kdl ;;
	"niri-animations") $EDITOR ~/.config/niri/config.d/animations.kdl ;;
	"niri-windows") $EDITOR ~/.config/niri/config.d/windows.kdl ;;
	"niri-colors") $EDITOR ~/.config/niri/config.d/colors.kdl ;;
	"niri-keyboard") $EDITOR ~/.config/niri/config.d/binds/keyboard.kdl ;;
	"niri-mouse") $EDITOR ~/.config/niri/config.d/binds/mouse.kdl ;;
	"niri-macropad") $EDITOR ~/.config/niri/config.d/binds/macropad.kdl ;;
	"mpd") $EDITOR ~/.config/mpd/mpd.conf ;;
	"mpd-service") sudo $EDITOR /usr/lib/systemd/user/mpd.service ;;
	"rmpc") $EDITOR ~/.config/rmpc/config.ron ;;
	"rmpc-theme") $EDITOR ~/.config/rmpc/themes/kaputt.ron ;;
	"kitty") $EDITOR ~/.config/kitty/kitty.conf ;;
	"kitty-colors") $EDITOR ~/.config/wallust/templates/kitty ;;
	"kitty-startup") $EDITOR ~/.config/kitty/startup.sh ;;
	"nvim") $EDITOR ~/.config/nvim/init.lua ;;
	"toxic") $EDITOR ~/.config/tox/toxic.conf ;;
	"gtk3") $EDITOR ~/.config/gtk-3.0/settings.ini ;;
	"gtk4") $EDITOR ~/.config/gtk-4.0/settings.ini ;;
	"fonts") $EDITOR ~/.config/fontconfig/fonts.conf ;;
	"doio") $EDITOR ~/MDL/wastes/kb16_01.layout.json ;;
	"zsh") $EDITOR ~/.zshrc ;;
	"zsh-als") $EDITOR ~/.oh-my-zsh/custom/als.zsh ;;
	"zsh-env") $EDITOR ~/.oh-my-zsh/custom/env.zsh ;;
	"zsh-theme") $EDITOR ~/.oh-my-zsh/custom/themes/vira.zsh-theme ;;
	"wallust") $EDITOR ~/.config/wallust/wallust.toml ;;
	"cava") $EDITOR ~/.config/wallust/templates/cava ;;
	"drift") $EDITOR ~/.config/wallust/templates/drift ;;
	"alacritty") $EDITOR ~/.config/alacritty/alacritty.toml ;;
	"fastfetch") $EDITOR ~/.config/fastfetch/config.jsonc ;;
	"dirs") $EDITOR ~/.config/user-dirs.dirs ;;
	"greetd") sudo $EDITOR /etc/greetd/config.toml ;;
	"greetd-sway") sudo $EDITOR /etc/greetd/sway-config ;;
	"greetd-font") sudo $EDITOR /etc/greetd/font.css ;;
	"greetd-gtk3") sudo $EDITOR /var/lib/greetd/.config/gtk-3.0/settings.ini ;;
	"fstab") sudo $EDITOR /etc/fstab ;;
	"btop") $EDITOR ~/.config/btop/btop.conf ;;
	"yazi") $EDITOR ~/.config/yazi/yazi.toml ;;
	"yazi-theme") $EDITOR ~/.config/yazi/theme.toml ;;
	"yazi-keymap") $EDITOR ~/.config/yazi/keymap.toml ;;
	"wiremix") $EDITOR ~/.config/wiremix/wiremix.toml ;;
	*)
		echo "[cfg!] configuration shortcut [ ${cmd[0]} ] not defined"
		echo "[cfg/] aborting"
		exit 1
		;;
esac
